# --------------------------------------------
# SPRING
# --------------------------------------------
spring:
  application:
    name: school-management-app
  datasource:
    url: jdbc:postgresql://localhost:5432/school-management-app
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  jackson:
    time-zone: UTC


# --------------------------------------------
# SERVER
# --------------------------------------------
server:
  port: 8080

# --------------------------------------------
# JWT
# --------------------------------------------
jwt:
  secret: AVERYLONGSECRETKEYAVERYLONGSECRETKEYAVERYLONGSECRETKEYAVERYLONGSECRETKEYAVERYLONGSECRETKEYAVERYLONGSECRETKEY
  access-token-expiration-ms: 86400000
  refresh-token-expiration-ms: 604800000