CREATE TABLE academic_terms
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    institution_id BIGINT                                  NOT NULL,
    name           VARCHAR(255),
    start_date     date,
    end_date       date,
    status         VARCHAR(255),
    is_current     BOOLEAN,
    deleted_at     TIMESTAMPTZ,
    deleted_by     VARCHAR(255),
    CONSTRAINT pk_academic_terms PRIMARY KEY (id)
);

ALTER TABLE academic_terms
    ADD CONSTRAINT uc_academic_terms_uuid UNIQUE (uuid);

ALTER TABLE academic_terms
    ADD CONSTRAINT FK_ACADEMIC_TERMS_ON_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institutions (id);