CREATE TABLE user_roles
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    user_id        BIGINT                                  NOT NULL,
    role_id        BIGINT                                  NOT NULL,
    institution_id BIGINT,
    CONSTRAINT pk_user_roles PRIMARY KEY (id)
);

ALTER TABLE user_roles
    ADD CONSTRAINT uc_bf4e2a63fd1ff1e8dddc9e48e UNIQUE (user_id, role_id, institution_id);

ALTER TABLE user_roles
    ADD CONSTRAINT uc_user_roles_uuid UNIQUE (uuid);

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USER_ROLES_ON_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institutions (id);

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USER_ROLES_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USER_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);