CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at  TIMESTAMPTZ,
    deleted_by  VARCHAR(255),
    uuid        UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMPTZ,
    updated_at  TIMESTAMPTZ,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    actor_type  VARCHAR(255)                            NOT NULL,
    status      VARCHAR(255),
    is_default_role BOOLEAN DEFAULT false,
    is_super_admin BOOLEAN DEFAULT false,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_uuid UNIQUE (uuid);