CREATE TABLE user_institution_roles
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    institution_role_id        BIGINT                      NOT NULL,
    user_id  BIGINT,
    institution_id BIGINT,
    CONSTRAINT pk_user_institution_roles PRIMARY KEY (id)
);

ALTER TABLE user_institution_roles
    ADD CONSTRAINT uc_user_institution_roles_uuid UNIQUE (uuid);

ALTER TABLE user_institution_roles
    ADD CONSTRAINT FK_USER_INSTITUTION_ROLE_ON_ROLE FOREIGN KEY (institution_role_id) REFERENCES institution_roles (id);

ALTER TABLE user_institution_roles
    ADD CONSTRAINT FK_USER_INSTITUTION_ROLE_ON_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institutions (id);

ALTER TABLE user_institution_roles
    ADD CONSTRAINT FK_USER_INSTITUTION_ROLE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);