CREATE TABLE institution_role_permissions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    institution_role_id        BIGINT                      NOT NULL,
    permission_id  BIGINT,
    institution_id BIGINT,
    CONSTRAINT pk_institution_role_permissions PRIMARY KEY (id)
);

ALTER TABLE institution_role_permissions
    ADD CONSTRAINT uc_institution_role_permissions_uuid UNIQUE (uuid);

ALTER TABLE institution_role_permissions
    ADD CONSTRAINT FK_INSTITUTION_ROLE_PERMISSIONS_ON_ROLE FOREIGN KEY (institution_role_id) REFERENCES institution_roles (id);

ALTER TABLE institution_role_permissions
    ADD CONSTRAINT FK_INSTITUTION_ROLE_PERMISSIONS_ON_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institutions (id);

ALTER TABLE institution_role_permissions
    ADD CONSTRAINT FK_INSTITUTION_ROLE_PERMISSIONS_ON_PERMISSIONS FOREIGN KEY (permission_id) REFERENCES permissions (id);