-- Enable pgcrypto extension for gen_random_uuid() if not already enabled
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create institutions table
CREATE TABLE institutions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         UUID NOT NULL DEFAULT gen_random_uuid(),
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(255),
    code         VARCHAR(255),
    type         VARCHAR(255),
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    address      VARCHAR(255),
    status       VARCHAR(255)
);

-- Add unique constraint to uuid
ALTER TABLE institutions
    ADD CONSTRAINT uc_institutions_uuid UNIQUE (uuid);