CREATE TABLE academic_levels
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    deleted_at     TIMESTAMPTZ,
    deleted_by     VARCHAR(255),
    institution_id BIGINT                                  NOT NULL,
    name           VARCHAR(255),
    order_index    INTEGER DEFAULT 0,

    CONSTRAINT pk_academic_levels PRIMARY KEY (id)
);

ALTER TABLE academic_levels
    ADD CONSTRAINT uc_academic_levels_uuid UNIQUE (uuid);

ALTER TABLE academic_levels
    ADD CONSTRAINT FK_ACADEMIC_TERMS_ON_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institutions (id);