CREATE TABLE grade_levels
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    deleted_at     TIMESTAMPTZ,
    deleted_by     VARCHAR(255),
    institution_id BIGINT                                  NOT NULL,
    academic_level_id BIGINT                                  NOT NULL,
    name           VARCHAR(255),
    code           VARCHAR(255),
    order_index    INTEGER DEFAULT 0,

    CONSTRAINT pk_grade_levels PRIMARY KEY (id)
);

ALTER TABLE grade_levels
    ADD CONSTRAINT uc_grade_levels_uuid UNIQUE (uuid);

ALTER TABLE grade_levels
    ADD CONSTRAINT FK_ACADEMIC_TERMS_ON_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institutions (id);

ALTER TABLE grade_levels
    ADD CONSTRAINT FK_ACADEMIC_TERMS_ON_CLASS_LEVEL FOREIGN KEY (academic_level_id) REFERENCES academic_levels (id);