CREATE TABLE role_permissions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    role_id        BIGINT                                  NOT NULL,
    permission_id  BIGINT,
    CONSTRAINT pk_role_permissions PRIMARY KEY (id)
);

ALTER TABLE role_permissions
    ADD CONSTRAINT uc_role_permissions_uuid UNIQUE (uuid);

ALTER TABLE role_permissions
    ADD CONSTRAINT FK_ROLE_PERMISSION_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT FK_ROLE_PERMISSION_ON_INSTITUTION FOREIGN KEY (permission_id) REFERENCES permissions (id);