CREATE TABLE master_academic_classes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    deleted_at     TIMESTAMPTZ,
    deleted_by     VARCHAR(255),
    institution_id BIGINT                                  NOT NULL,
    grade_level_id BIGINT                                  NOT NULL,
    name           VARCHAR(255),
    code           VARCHAR(255),
    order_index    INTEGER DEFAULT 0,

    CONSTRAINT pk_master_academic_classes PRIMARY KEY (id)
);

ALTER TABLE master_academic_classes
    ADD CONSTRAINT uc_master_academic_classes_uuid UNIQUE (uuid);

ALTER TABLE master_academic_classes
    ADD CONSTRAINT FK_ACADEMIC_TERMS_ON_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institutions (id);

ALTER TABLE master_academic_classes
    ADD CONSTRAINT FK_ACADEMIC_TERMS_ON_GRADE_LEVEL FOREIGN KEY (grade_level_id) REFERENCES grade_levels (id);