CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at     TIMESTAMPTZ,
    deleted_by     VARCHAR(255),
    uuid           UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    username       VARCHAR(255),
    password       VARCHAR(255),
    email          VARCHAR(255),
    status         VARCHAR(255),
    type           VARCHAR(255),
    institution_id BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_uuid UNIQUE (uuid);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institutions (id);