CREATE TABLE institution_roles
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_by     VARCHAR(255),
    uuid           UUID DEFAULT gen_random_uuid()          NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    name           VARCHAR(255)                            NOT NULL,
    description    VARCHAR(255),
    actor_type     VARCHAR(255)                            NOT NULL,
    institution_id BIGINT                                  NOT NULL,
    base_role_id   BIGINT,
    status         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_institution_roles PRIMARY KEY (id)
);

ALTER TABLE institution_roles
    ADD CONSTRAINT uc_institution_roles_uuid UNIQUE (uuid);

ALTER TABLE institution_roles
    ADD CONSTRAINT FK_INSTITUTION_ROLES_ON_BASE_ROLE FOREIGN KEY (base_role_id) REFERENCES roles (id);

ALTER TABLE institution_roles
    ADD CONSTRAINT FK_INSTITUTION_ROLES_ON_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institutions (id);